import React, { useState } from 'react'
import { useRouter } from 'next/router'

const Instructions = () => {
  const [checked, setChecked] = useState(false);

  const [q1, setQ1] = useState(false);
  const [q2, setQ2] = useState(false);
  const [q3, setQ3] = useState(false);
  const [q4, setQ4] = useState(false);
  const [q5, setQ5] = useState(false);

  const router = useRouter();

  const next = () => {
    if (!(q1 && !q2 && q3 && q4 && !q5)) {
      alert('Please carefully read the instructions to answer the questions correctly!');
      return;
    }
    router.push('/td-instructions');
  };

  return (
    <div className="content">
      <h1>Suzzle Tutor</h1>
      <p>
        In this experiment, you will learn about a puzzle called Suzzle,
        where you need to move shapes  according to certain rules to reach a goal.
        We are interested in how different methods can help humans learn.
        The experiment should take around 25 minutes, excluding the time it takes
        to read the instructions. You may only do this task once.
    </p>

    <p>
      The experiment will have 3 phases:
    </p>
    <ol>
      <li>First, you are going to read an explanation of the rules and goals of Suzzle.</li>
      <li>
        Then, you will go through a session of exercises generated by a computer that aim at
        helping you learn to solve the puzzle.
        This section will be over once you answer 20 exercises, or after 20 minutes have elapsed since you started.
        Answering incorrectly wil lead to a step-by-step solution. The step-by-step explanation might take up to one minute in longer puzzles, and it is completely skipped
        if your answer is right.
        Therefore, <em>trying your best to answer each exercise will help you finish the HIT in less time</em>.</li>
      <li>
        Finally, you will take a 3-minute test to evaluate how well you've learned to Suzzle.
        In this session, you will not see the true answers to each puzzle.
      </li>
    </ol>

    <p>
      By following the instructions, you are participating in a study being performed by
      cognitive scientists in the Stanford Department of Psychology.
      If you have questions about this research, please contact Gabriel Poesia at poesia@stanford.edu
      or Noah Goodman at ngoodman@stanford.edu.
    </p>

    <h2>Consent</h2>

    <ul>
      <li>You must be at least 18 years old to participate.</li>
      <li>Your participation in this research is voluntary.</li>
      <li>You may decline to answer any or all of the following questions.</li>
      <li>You may decline further participation, at any time, without adverse consequences.</li>
      <li>Your anonymity is assured; the researchers who have requested your participation will not receive any personally identifying information.</li>
    </ul>

    <p>
      <input type="checkbox" value={checked} onChange={() => setChecked(!checked)} />
      <span>I have read and agree with the above.</span>
    </p>

    <h2>Checking your understanding</h2>

    <p>To start the experiment, please check only the options that are true:</p>

    <ul className="invisible-list">
      <li><input type="checkbox" value={q1} onChange={() => setQ1(!q1)} /><span>The experiment involves learning about a puzzle, a sequence of exercises and a test.</span></li>
      <li><input type="checkbox" value={q2} onChange={() => setQ2(!q2)} /><span>The exercises involve typing sentences in English.</span></li>
      <li><input type="checkbox" value={q3} onChange={() => setQ3(!q3)} /><span>Solving exercises correctly will allow me to finish the HIT faster.</span></li>
      <li><input type="checkbox" value={q4} onChange={() => setQ4(!q4)} /><span>In "AABAC", swapping the order of the last two characters gives "AABCA"</span></li>
        <li><input type="checkbox" value={q5} onChange={() => setQ5(!q5)} /><span>In "ABZBA", erasing the character "Z" results in "ABB".</span></li>
    </ul>

    <button disabled={!checked} onClick={next}>Continue</button>

    </div>
  );
};
export default Instructions;
