import React, { useState } from 'react'
import { useRouter } from 'next/router'

const Instructions = () => {
  const [checked, setChecked] = useState(false);

  const [q1, setQ1] = useState(false);
  const [q2, setQ2] = useState(false);
  const [q3, setQ3] = useState(false);
  const [q4, setQ4] = useState(false);
  const [q5, setQ5] = useState(false);

  const router = useRouter();

  const next = () => {
    if (!(q1 && !q2 && q3 && q4 && !q5)) {
      alert('Please carefully read the instructions to answer the questions correctly!');
      return;
    }
    router.push('/assessment?stage=pre');
  };

  return (
    <div className="content">
      <h1>Algebra Tutor :: Human Evaluation</h1>
      <p>
        In this experiment, you will solve algebra exercises generated by a computer agent that
        is trying to maximize student learning. It will take a maximum of 26 minutes,
        excluding the time it takes to read these instructions.
        You may only do this task once.
    </p>

    <p>
      The experiment will have 3 phases:
    </p>
    <ol>
      <li>First, you are going to take a 3-minute test, where you will be asked to solve a few equations.</li>
      <li>
        Then, you will go through a sessions of multiple-choice exercises generated by a computer that aim at
        helping you learn algebra. This section will be over once you successfully answer 20 exercises, or after 20 minutes have elapsed since you started.
        Answering incorrectly makes the system pause for 10 seconds so that you can understand the other options in the exercise.
        Therefore, <em>trying your best to answer each exercise will help you finish the HIT in less time</em>.</li>
      <li>Finally, you will take another 3-minute test just like the first one, but with different equations.</li>
    </ol>

    <p>
      By following the typing task instructions, you are participating in a study being performed by
      cognitive scientists in the Stanford Department of Psychology.
      If you have questions about this research, please contact Gabriel Poesia at poesia@stanford.edu
      or Noah Goodman at ngoodman@stanford.edu.
    </p>

    <h2>Consent</h2>

    <ul>
      <li>You must be at least 18 years old to participate.</li>
      <li>Your participation in this research is voluntary.</li>
      <li>You may decline to answer any or all of the following questions.</li>
      <li>You may decline further participation, at any time, without adverse consequences.</li>
      <li>Your anonymity is assured; the researchers who have requested your participation will not receive any personal information about you.</li>
    </ul>

    <p>
      <input type="checkbox" value={checked} onChange={() => setChecked(!checked)} />
      <span>I have read and agree with the above.</span>
    </p>

    <h2>Checking your understanding</h2>

    <p>To start the experiment, please check only the options that are true:</p>

    <ul className="invisible-list">
      <li><input type="checkbox" value={q1} onChange={() => setQ1(!q1)} /><span>The experiment involves two tests and a set of exercises.</span></li>
      <li><input type="checkbox" value={q2} onChange={() => setQ2(!q2)} /><span>The exercises involve typing sentences in English.</span></li>
      <li><input type="checkbox" value={q3} onChange={() => setQ3(!q3)} /><span>Solving exercises correctly will allow me to finish the HIT faster.</span></li>
      <li><input type="checkbox" value={q4} onChange={() => setQ4(!q4)} /><span>In the equation <em>x = 5 - 1</em>, the solution for x is 4.</span></li>
      <li><input type="checkbox" value={q5} onChange={() => setQ5(!q5)} /><span>In the equation <em>x = 2 + 2</em>, the solution for x is 5.</span></li>
    </ul>

    <button disabled={!checked} onClick={next}>Continue</button>

    </div>
  );
};
export default Instructions;
